config/routes.rb
Rails.application.routes.draw do
  resources :boards
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
require 'hypernova'

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  around_action :hypernova_render_support
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:title, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_errors.html.erb
<% if board.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

    <ul>
    <% board.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/boards/_form.html.erb
<%= form_with(model: board, local: true) do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :board_title %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message, id: :board_message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boards</h1>

<%= render_react_component('Board', { boards: @boards}) %>

<br>

<%= link_to 'New Board', new_board_path %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'errors', board: @board %>
<%= render_react_component('BoardForm', { board: @board, token: form_authenticity_token, submitText: 'Create Board'}) %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @board.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @board.message %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>TutorialBlog</title>
    <%= csrf_meta_tags %>

    <meta name="turbolinks-cache-control" content="no-preview">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>